name: 4. Build Loop
run-name: Build Loop ${{ github.ref_name }}
on:
  workflow_dispatch:
  
  ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
  #push:

  ## Remove the "#" sign from the beginning of the two lines below to get automated builds every two months
  #schedule:
    #- cron: '0 17 1 */2 *' # Runs at 17:00 UTC on the 1st in Jan, Mar, May, Jul, Sep and Nov.

jobs:
  secrets:
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
    
  build:
    needs: secrets
    runs-on: macos-12
    steps:
      # Uncomment to manually select latest Xcode if needed
      - name: Select Latest Xcode
        run: "sudo xcode-select --switch /Applications/Xcode_14.1.app/Contents/Developer"

      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
           
      # Customize Loop: Download and apply patches
      - name: Customize Loop
        run: |
        
          # BEGINNING: apply the lnl_patches to the released code
          # See: https://www.loopandlearn.org/main-lnl-patches
          
          # LoopWorkspace commit: Adds xDrip4iOS and GlucoseDirect CGM clients
          # Note - the added submodules must be cloned before the patch will work
          git clone https://github.com/johandegraeve/xdrip-client-swift-1.git xdrip-client-swift
          git clone https://github.com/creepymonster/GlucoseDirectClient.git GlucoseDirectClient
          # This patch configures LoopWorkspace to use the added CGM submodules
          curl https://github.com/loopnlearn/LoopWorkspace/commit/4092277a21fa44a1258b693a5fbcce4d8d9dbd17.patch | git apply

          # LoopWorkspace commit: Merge pull request to add LoopnLearn logo (from MikePlante1)
          curl https://github.com/loopnlearn/LoopWorkspace/commit/7c1dd02e74508a171128de85741e44b09ccee118.patch | git apply

          # These next two patches must be combined together, do not apply one without the other
          # This applies CustomTypeOne LoopPatches to released submodules Loop and LoopKit
          # See: https://www.loopandlearn.org/custom-type-one-loop-patches
          curl https://raw.githubusercontent.com/CustomTypeOne/LoopPatches/main/LoopPatch.txt | git apply --directory=Loop
          curl https://raw.githubusercontent.com/CustomTypeOne/LoopPatches/main/LoopkitPatch.txt | git apply --directory=LoopKit

          # END: lnl_patches now applied to the released code
          
          # additional patches can be put below - make sure columns line up
             
          # Loop: Increase future carb time limit to 4 hours from 1 hour default
          curl https://github.com/loopnlearn/Loop/commit/a974b6749ef4506ca679a0061c260dabcfbf9ee2.patch | git apply --directory=Loop
          
          # LoopKit: Disable authentication for bolusing and therapy setting changes
          curl https://github.com/loopnlearn/LoopKit/commit/77ee44534dd16154d910cfb11dea240cf8a23262.patch | git apply --directory=LoopKit
                  
          # OmniBLE: CAGE: Upload to Nightscout when DASH pod is started
          curl https://github.com/loopnlearn/OmniBLE/commit/8fad98f197862928b24ea7af26aff38f39b4bba6.patch | git apply --directory=OmniBLE
                  
          # CGMBLEKit: SAGE: Upload to Nightscout when G5 or G6 sensor is started
          curl https://github.com/loopnlearn/CGMBLEKit/commit/777c7e36de64bdc060973a6628a02add0917520e.patch | git apply --directory=CGMBLEKit
                  
          # CGMBLEKit: Modify default setting to upload CGM readings to remote service
          curl https://github.com/loopnlearn/CGMBLEKit/commit/b9638cc7cef74b1da74c950c0dbb3525f157e11f.patch | git apply --directory=CGMBLEKit
          
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Build signed Loop IPA file
      - name: Fastlane Build & Archive
        run: fastlane build_loop
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      # Upload to TestFlight
      - name: Fastlane upload to TestFlight
        run: fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Upload IPA and Symbols
      - name: Upload IPA and Symbol artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
